# -*- coding: utf-8 -*-
"""menuForIf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/126pNhCrTi6u171H8TOtGeZwNm4F50w8L
"""

# Jitender RajpootMenu Program
# Create a menu.
name = input("What's is you name? ")
color = input("What is your favorite color? ")
counter = 0
print("Hello," , name)
menuInput = (input("For Name: enter 1; for Color: Enter 2; for Counter: Enter 3; to Quit: Enter 4"))
for item in menuInput:
  while menuInput == "1" or "2" or "3" or "4":

    if item == "1":
      counter += 1
      print("Your name is: ", name)
    elif item == "2":
      counter += 1
      print("Your favorite color is: ", color)
    elif item == "3":
      counter += 1
      print("The counter is: ", counter)
    elif item == "4":
      counter += 1
      print("Thank you. You chose to quit program")
    break


# Say Hello

# Favorite Color

# Counter

# Quit

# Keep showing the menu until the user chooses 4.

#Jitender Rajpoot
choice = 0
name = input("What's your name? ")
while choice != 4:
  print("1. Say Hello")
  print("2. Favorite Color")
  print("3. Counter")
  print("4. Quit")

  choice = int(input("Choose an option: "))

  if choice == 1:
    print("Hello!", name)

  elif choice == 2:
    color = input("What's your favorite color? ")
    print(name, ", your favorite coloe is ", color, ".")

  elif choice == 3:
    for number in range(1, 6):
      print(number)

  elif choice == 4:
    print("Goodbye!")

  else:
    print("Invalid choice, Please choose 1-4.:")

import matplotlib.pyplot as plt   #import lib create graphs
                                  #pyplot functions make graphs; plt short name
def visualize_sorting(data):    #function takes data as argument
  plt.bar(range(len(data)), data) #len counts items in list 'data'; range represents positions of items in list
                                  #plt.bar creates bar graph range=x axis; data=y axis
  plt.show()        #display graph
data = [3,1,4,1,5,9,2,6,5,3,5] #y axis = data; height of bar=value in list
visualize_sorting(data)   #

import this

def bubble_sort(arr):   #function takes arr=list to sort as argument
  n = len(arr)        #len counts items in list
  for i in range(n):  #outer loop
    swapped = False   #assume nothing swapped at start
    for j in range(0, n-i-1):   #inner loop compares neighboring nums; j=current position
                                #compare num immediately to its right
      if arr[j] > arr[j+1]:   #is num on left nigger than num on right?
        arr[j], arr[j+1] = arr[j+1], arr[j]   #swap if num on right larger
        swapped = True  #if we swap numbers change false variable to true
    if not swapped:   #if no swaps happen
        break           #stop loop
  return arr            #send sorted list when function called

sample_list = [4,2,8,1,5]
sorted_list = bubble_sort(sample_list)
print(sorted_list)