# -*- coding: utf-8 -*-
"""jrajpoot4.4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wnrqxcFFowq_TOKOr7Uo5QQwnTCs-n-_
"""

#Jitender Rajpoot

f = float(input("Enter temperature"))

def convert(f):
  c = (f-32) * (5/9)
  print(f, "Fahrenheit in Celsius is: ")
  return(c)

convert(f)